apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: hypercloud5-system
type: Opaque
data:
  ROOT_PASSWORD: dG1heA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: hypercloud5-system
data:
  retention.hour: "90"
  retention.day: "365"
  retention.month: "3650"
  initdb.sql: |
    create table metering.metering (id varchar(64) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,gpu double,public_ip int,private_ip int, traffic_in bigint, traffic_out bigint, metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    alter table metering.metering add constraint unique_metering unique (namespace, metering_time);
    create table metering.metering_hour (id varchar(64) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,gpu double,public_ip int,private_ip int, traffic_in bigint, traffic_out bigint, metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    alter table metering.metering_hour add constraint unique_metering_hour unique (namespace, metering_time);
    create table metering.metering_day (id varchar(64) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,gpu double,public_ip int,private_ip int, traffic_in bigint, traffic_out bigint, metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    alter table metering.metering_day add constraint unique_metering_day unique (namespace, metering_time);
    create table metering.metering_month (id varchar(64) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,gpu double,public_ip int,private_ip int, traffic_in bigint, traffic_out bigint, metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    alter table metering.metering_month add constraint unique_metering_month unique (namespace, metering_time);
    create table metering.metering_year (id varchar(64) not null,namespace varchar(255) not null,cpu double,memory bigint,storage bigint,gpu double,public_ip int,private_ip int, traffic_in bigint, traffic_out bigint, metering_time timestamp not null default current_timestamp,status varchar(255),primary key (id));
    alter table metering.metering_year add constraint unique_metering_year unique (namespace, metering_time);
    
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: hypercloud5-system
spec:
  ports:
  - name: "mysql"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    hypercloud5: metering
  type: NodePort

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
  namespace: hypercloud5-system
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: hypercloud5-system
  labels:
    hypercloud5: metering
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud5: metering
  template:
    metadata:
      labels:
        hypercloud5: metering
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          subPath: mysql
          name: mysql-data
        - mountPath: /docker-entrypoint-initdb.d
          name: mysql-initdb-config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: metering
        - name: TZ
          value: Asia/Seoul
        resources:
          limits:
            cpu: "1"
            memory: "3Gi"
          requests:
            cpu: "1"
            memory: "300m"
      serviceAccountName: hypercloud5-admin
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: mysql-initdb-config
        configMap:
          name: mysql-initdb-config
