apiVersion: v1
kind: Service
metadata:
  name: hypercloud5-api-server-service
  namespace: hypercloud5-system
spec:
  ports:
  - port: 443
    targetPort: https
  selector:
    hypercloud5: api-server
  type: NodePort
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud5-api-server
  namespace: hypercloud5-system
  labels:
    hypercloud5: api-server
    name: hypercloud5-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud5: api-server
  template:
    metadata:
      name: hypercloud5-api-server
      namespace: hypercloud5-system
      labels:
        hypercloud5: api-server
    spec:
      serviceAccount: hypercloud5-admin
      containers:
        - name: hypercloud5-api-server
          image: tmaxcloudck/hypercloud-api-server:{HPCD_API_SERVER_VERSION}
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: HC_MODE
              value: {HPCD_MODE} # multi / single 
            - name: INVITATION_TOKEN_EXPIRED_DATE
              value: {INVITATION_TOKEN_EXPIRED_DATE} # multi / single 
            - name: GODEBUG
              value: "x509ignoreCN=0"  
            - name: SIDECAR_IMAGE
              value: "fluent/fluent-bit:1.5-debug"
          ports:
          - containerPort: 443
            name: https 
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "1"
              memory: "100M"
          volumeMounts:
          - name: version-config
            mountPath: /go/src/version/version.config
            subPath: version.config
          #- name: kafka
          #  mountPath: /go/src/etc/ssl
          - name: hypercloud5-api-server-certs
            mountPath: /run/secrets/tls
            readOnly: true
          - name: token-secret
            mountPath: /run/secrets/token
            readOnly: true
      volumes:
      - name : version-config
        configMap:
          name : version-config
      - name: hypercloud5-api-server-certs
        secret:
          secretName: hypercloud5-api-server-certs
        name: hypercloud5-api-server-certs 
      - name: smtp-secret
        secret:
          secretName: smtp-secret
          items:
          - key: SMTP_USERNAME
            path: username
          - key: SMTP_PASSWORD
            path: password
      #- name: kafka
      #  secret:
      #    secretName: hypercloud-kafka-secret2
      - name: token-secret
        secret:
          secretName: token-secret
          items:
          - key: ACCESS_TOKEN
            path: accessSecret
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  SMTP_USERNAME: bm8tcmVwbHktdGNAdG1heC5jby5rcg==
  SMTP_PASSWORD: IUB0Y2Ruc2R1ZHhsYTEx
---
apiVersion: v1
kind: Secret
metadata:
  name: token-secret
type: Opaque
data:
  ACCESS_TOKEN: dG1heEAxMw==

