apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: hypercloud5-api-server-kafka-cert
 namespace: hypercloud5-system
spec:
 secretName: hypercloud-kafka-secret
 isCA: false
 usages:
 - digital signature
 - key encipherment
 - server auth
 - client auth
 dnsNames:
 - "hypercloud5-api-server-service.hypercloud5-system.svc"
 issuerRef:
   kind: ClusterIssuer
   group: cert-manager.io
   name: tmaxcloud-issuer  
